services:
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trading_bot
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src
    env_file:
      - .env
    command: [ "python", "src/main.py" ]
    stdin_open: true # keeps STDIN open (nice for shells)
    tty: true # allocates a TTY (nice for interactive use)
